#!/bin/sh
# vhusbd rewrites its config.ini when you change settings from the client
# (license key, device nicknames, ...). Copy it back to the SD card when
# it changes, so it survives a reboot. The card is only writable for the
# moment it takes to copy.

. /etc/functions

cfg=/etc/vhusbd/config.ini
save() {
	cp "$cfg" /boot/config.ini.new && mv /boot/config.ini.new /boot/config.ini
}
while sleep 5; do
	[ -f "$cfg" ] || continue
	cmp -s "$cfg" /boot/config.ini && continue
	[ -e /dev/mmcblk0p1 ] || continue
	boot_rw save && echo "persist-config: saved config.ini to SD card" > /dev/console
done
